### ISSUE TITLE
Code Quality, Decomposition refactoring

### ISSUE THREAD

**Issue by artsiomtserashkovich** [ViachaslauPratasenia/PhoneShop#1]
Hello(Ky-Ky).
Today i've inspected your code and noticed that you have "fat" controller.
https://github.com/ViachaslauPratasenia/PhoneShop/blob/f06b39bd53b62c0094bc43a1f36cdf84029c5840/Code/src/main/java/com/es/phoneshop/web/CartPageServlet.java#L37-L41

May be better implement Business Logic layer and transfer this code to specific class.

**Comment by messi3nik** [comment]
Hi, guys! Is that issue still open? I'm afraid that we won't be able to solve it by the release date! Notice that app version is still 0.01.
@ArtemTereshkovich, please, take control.

**Comment by artsiomtserashkovich** [comment]
I think this repo is out-of-date.
